export const users = [
  {
    id: 1,
    firstName: "Terry",
    lastName: "Medhurst",
    maidenName: "Smitham",
    age: 50,
    gender: "male",
    email: "atuny0@sohu.com",
    phone: "+63 791 675 8914",
    username: "atuny0",
    birthDate: "2000-12-25",
  },
  {
    id: 2,
    firstName: "Sheldon",
    lastName: "Quigley",
    maidenName: "Cole",
    age: 28,
    gender: "male",
    email: "hbingley1@plala.or.jp",
    phone: "+7 813 117 7139",
    username: "hbingley1",
    birthDate: "2003-08-02",
  },
  {
    id: 3,
    firstName: "Terrill",
    lastName: "Hills",
    maidenName: "Hoeger",
    age: 38,
    gender: "male",
    email: "rshawe2@51.la",
    phone: "+63 739 292 7942",
    username: "rshawe2",
    birthDate: "1992-12-30",
  },
  {
    id: 4,
    firstName: "Miles",
    lastName: "Cummerata",
    maidenName: "Maggio",
    age: 49,
    gender: "male",
    email: "yraigatt3@nature.com",
    phone: "+86 461 145 4186",
    username: "yraigatt3",
    birthDate: "1969-01-16",
  },
  {
    id: 5,
    firstName: "Mavis",
    lastName: "Schultz",
    maidenName: "Yundt",
    age: 38,
    gender: "male",
    email: "kmeus4@upenn.edu",
    phone: "+372 285 771 1911",
    username: "kmeus4",
    birthDate: "1968-11-03",
  },
  {
    id: 6,
    firstName: "Alison",
    lastName: "Reichert",
    maidenName: "Franecki",
    age: 21,
    gender: "female",
    email: "jtreleven5@nhs.uk",
    phone: "+351 527 735 3642",
    username: "jtreleven5",
    birthDate: "1969-07-21",
  },
  {
    id: 7,
    firstName: "Oleta",
    lastName: "Abbott",
    maidenName: "Wyman",
    age: 31,
    gender: "female",
    email: "dpettegre6@columbia.edu",
    phone: "+62 640 802 7111",
    username: "dpettegre6",
    birthDate: "1982-02-21",
  },
  {
    id: 8,
    firstName: "Ewell",
    lastName: "Mueller",
    maidenName: "Durgan",
    age: 29,
    gender: "male",
    email: "ggude7@chron.com",
    phone: "+86 946 297 2275",
    username: "ggude7",
    birthDate: "1964-08-24",
  },
  {
    id: 9,
    firstName: "Demetrius",
    lastName: "Corkery",
    maidenName: "Gleason",
    age: 22,
    gender: "male",
    email: "nloiterton8@aol.com",
    phone: "+86 356 590 9727",
    username: "nloiterton8",
    birthDate: "1971-03-11",
  },
  {
    id: 10,
    firstName: "Eleanora",
    lastName: "Price",
    maidenName: "Cummings",
    age: 37,
    gender: "female",
    email: "umcgourty9@jalbum.net",
    phone: "+60 184 408 0824",
    username: "umcgourty9",
    birthDate: "1958-08-11",
  },
  {
    id: 11,
    firstName: "Marcel",
    lastName: "Jones",
    maidenName: "Smith",
    age: 39,
    gender: "male",
    email: "acharlota@liveinternet.ru",
    phone: "+967 253 210 0344",
    username: "acharlota",
    birthDate: "1961-09-12",
  },
  {
    id: 12,
    firstName: "Assunta",
    lastName: "Rath",
    maidenName: "Heller",
    age: 42,
    gender: "female",
    email: "rhallawellb@dropbox.com",
    phone: "+380 962 542 6549",
    username: "rhallawellb",
    birthDate: "1990-12-14",
  },
  {
    id: 13,
    firstName: "Trace",
    lastName: "Douglas",
    maidenName: "Lemke",
    age: 26,
    gender: "male",
    email: "lgribbinc@posterous.com",
    phone: "+1 609 937 3468",
    username: "lgribbinc",
    birthDate: "1967-07-23",
  },
  {
    id: 14,
    firstName: "Enoch",
    lastName: "Lynch",
    maidenName: "Heidenreich",
    age: 21,
    gender: "male",
    email: "mturleyd@tumblr.com",
    phone: "+94 912 100 5118",
    username: "mturleyd",
    birthDate: "1979-08-25",
  },
  {
    id: 15,
    firstName: "Jeanne",
    lastName: "Halvorson",
    maidenName: "Cummerata",
    age: 26,
    gender: "female",
    email: "kminchelle@qq.com",
    phone: "+86 581 108 7855",
    username: "kminchelle",
    birthDate: "1996-02-02",
  },
  {
    id: 16,
    firstName: "Trycia",
    lastName: "Fadel",
    maidenName: "Rosenbaum",
    age: 41,
    gender: "female",
    email: "dpierrof@vimeo.com",
    phone: "+420 833 708 0340",
    username: "dpierrof",
    birthDate: "1963-07-03",
  },
  {
    id: 17,
    firstName: "Bradford",
    lastName: "Prohaska",
    maidenName: "Bins",
    age: 43,
    gender: "male",
    email: "vcholdcroftg@ucoz.com",
    phone: "+420 874 628 3710",
    username: "vcholdcroftg",
    birthDate: "1975-10-20",
  },
  {
    id: 18,
    firstName: "Arely",
    lastName: "Skiles",
    maidenName: "Monahan",
    age: 42,
    gender: "male",
    email: "sberminghamh@chron.com",
    phone: "+55 886 766 8617",
    username: "sberminghamh",
    birthDate: "1958-02-05",
  },
  {
    id: 19,
    firstName: "Gust",
    lastName: "Purdy",
    maidenName: "Abshire",
    age: 46,
    gender: "male",
    email: "bleveragei@so-net.ne.jp",
    phone: "+86 886 889 0258",
    username: "bleveragei",
    birthDate: "1989-10-15",
  },
  {
    id: 20,
    firstName: "Lenna",
    lastName: "Renner",
    maidenName: "Schumm",
    age: 41,
    gender: "female",
    email: "aeatockj@psu.edu",
    phone: "+1 904 601 7177",
    username: "aeatockj",
    birthDate: "1980-01-19",
  },
  {
    id: 21,
    firstName: "Doyle",
    lastName: "Ernser",
    maidenName: "Feeney",
    age: 23,
    gender: "male",
    email: "ckensleyk@pen.io",
    phone: "+86 634 419 6839",
    username: "ckensleyk",
    birthDate: "1983-01-22",
  },
  {
    id: 22,
    firstName: "Tressa",
    lastName: "Weber",
    maidenName: "Williamson",
    age: 41,
    gender: "female",
    email: "froachel@howstuffworks.com",
    phone: "+34 517 104 6248",
    username: "froachel",
    birthDate: "1987-11-11",
  },
  {
    id: 23,
    firstName: "Felicity",
    lastName: "O'Reilly",
    maidenName: "Rosenbaum",
    age: 46,
    gender: "female",
    email: "beykelhofm@wikispaces.com",
    phone: "+63 919 564 1690",
    username: "beykelhofm",
    birthDate: "1967-10-05",
  },
  {
    id: 24,
    firstName: "Jocelyn",
    lastName: "Schuster",
    maidenName: "Dooley",
    age: 19,
    gender: "male",
    email: "brickeardn@fema.gov",
    phone: "+7 968 462 1292",
    username: "brickeardn",
    birthDate: "1966-06-02",
  },
  {
    id: 25,
    firstName: "Edwina",
    lastName: "Ernser",
    maidenName: "Kiehn",
    age: 21,
    gender: "female",
    email: "dfundello@amazon.co.jp",
    phone: "+86 376 986 8945",
    username: "dfundello",
    birthDate: "2000-09-28",
  },
  {
    id: 26,
    firstName: "Griffin",
    lastName: "Braun",
    maidenName: "Deckow",
    age: 35,
    gender: "male",
    email: "lgronaverp@cornell.edu",
    phone: "+62 511 790 0161",
    username: "lgronaverp",
    birthDate: "1965-09-06",
  },
  {
    id: 27,
    firstName: "Piper",
    lastName: "Schowalter",
    maidenName: "Wuckert",
    age: 47,
    gender: "female",
    email: "fokillq@amazon.co.jp",
    phone: "+60 785 960 7918",
    username: "fokillq",
    birthDate: "1983-06-07",
  },
  {
    id: 28,
    firstName: "Kody",
    lastName: "Terry",
    maidenName: "Larkin",
    age: 28,
    gender: "male",
    email: "xisherwoodr@ask.com",
    phone: "+81 859 545 8951",
    username: "xisherwoodr",
    birthDate: "1979-01-09",
  },
  {
    id: 29,
    firstName: "Macy",
    lastName: "Greenfelder",
    maidenName: "Koepp",
    age: 45,
    gender: "female",
    email: "jissetts@hostgator.com",
    phone: "+81 915 649 2384",
    username: "jissetts",
    birthDate: "1976-09-07",
  },
  {
    id: 30,
    firstName: "Maurine",
    lastName: "Stracke",
    maidenName: "Abshire",
    age: 31,
    gender: "female",
    email: "kdulyt@umich.edu",
    phone: "+48 143 590 6847",
    username: "kdulyt",
    birthDate: "1964-12-18",
  },
];
export const fetchUser = async () => {
  return await users;
};

export const addUser = (user) => {
  const {
    firstName,
    lastName,
    username,
    maidenName = "",
    email,
    age,
    phone,
    birthDate,
  } = user;
  let length = users.length;
  users.push({
    firstName,
    maidenName,
    lastName,
    username,
    email,
    age,
    phone,
    birthDate,
    id: length,
  });
  return users.length > length ? "User is Added" : "User is not added";
};

export const search = async (obj) => {
  const res = await users.filter((u) => u[obj.key] === obj.value);

  return res;
};
